### PR TITLE
Mark OpenAMP as a system header

### PR DESCRIPTION
**Pull request by ljbade**
@jacobmcnamee Can you review

### CODE REVIEW

**Comment by jacobmcnamee** [comment]
The firmware also includes `env.h` and `hil.h`. That said, I'm not really wild about doing this to every library we pull in. What is the benefit exactly?

**Comment by ljbade** [comment]
@jacobmcnamee it allows us to enable more warnings in firmware to check our own code, that this library fails, specifically it does not use `foo(void)` for functions with no arguments.

I tried to do this in our make file but I couldn't get it too work. This works when I tested it.

@jacobmcnamee I was able to replace the include for `env.h` and `hil.h` with just `openamp.h` it appears they get included as part of `openamp.h`

**Comment by ljbade** [comment]
@jacobmcnamee an alternative would be to fix the problem causing the warnings, that is to modify all the headers to use `foo(void)`

**Comment by ljbade** [comment]
Closing to put `#pragma` around the `#includes`

**Pull request closed without merging**
